# Generated by Django 3.0.4 on 2020-11-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('relationship', 'Relationship'), ('father', 'Father'), ('mother', 'Mother'), ('husband', 'Husband'), ('wife', 'Wife'), ('brother', 'Brother'), ('sister', 'Sister'), ('son', 'Son'), ('daughter', 'Daughter')], default='relationship', max_length=12)),
                ('gender', models.CharField(choices=[('gender', 'Gender'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='gender', max_length=6)),
                ('image', models.ImageField(upload_to='images')),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=12)),
                ('ssn', models.IntegerField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
    ]
