# Generated by Django 3.0.4 on 2020-11-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kin', '0004_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='ssn',
            new_name='SSN',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='relationship',
            new_name='relationship_with_Mr_Fred_Swanson',
        ),
    ]
