# Generated by Django 3.0.4 on 2020-11-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kin', '0005_auto_20201120_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='back_view',
        ),
        migrations.AddField(
            model_name='document',
            name='front_view',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
