# Generated by Django 3.0.4 on 2020-11-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kin', '0006_auto_20201120_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='userdata',
            name='back_view',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='front_view',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
