# Generated by Django 3.0.4 on 2020-11-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kin', '0007_auto_20201120_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='back_view',
            new_name='Please_upload_valid_ID_back_view',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='front_view',
            new_name='Please_upload_valid_ID_front_view',
        ),
    ]
